"""empty message

Revision ID: de10932eff76
Revises: 45243ae00f15
Create Date: 2018-10-17 02:47:44.369262

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'de10932eff76'
down_revision = '45243ae00f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('uploded_by', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['uploded_by'],
                        ['users.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
